# Default application settings, which can be overridden locally and in each
# Rails environment (eg. development, test, production).
#
# See # https://github.com/railsjedi/rails_config for details.

# The following values are just placeholders and must be overridden (eg. in
# settngs.local.yml) for the corresponding features to work.

chef:
  server_url:  <%= ENV['CHEF_SERVER_URL']  || 'https://api.opscode.com' %>
  client_name: <%= ENV['CHEF_CLIENT_NAME'] || 'johndoe' %>
  client_key:  <%= ENV['CHEF_CLIENT_KEY']  || '/home/johndoe/chef-keys/johndoe.pem' %>

newrelic:
  account_id:     <%= ENV['NEWRELIC_ACCOUNT_ID']     || 12345  %>
  application_id: <%= ENV['NEWRELIC_APPLICATION_ID'] || 123456 %>
  api_key:        <%= ENV['NEWRELIC_API_ID']         || 'abcdefghijklmnopqrstuvwxyz' %>
